import { describe, expect, it, vi } from 'vitest';
import { generateKeyPairSync, sign } from 'node:crypto';
import { initializeMemoryDatabase } from '../memory/memoryDatabase';
import { AuditService } from '../auditService';
import { CompanionService } from './companionService';
import type { CompanionMessage } from '../../shared/companionTypes';

function setup(): { service: CompanionService; close: () => void } { const database = initializeMemoryDatabase(':memory:'); const audit = new AuditService(database.connection); return { service: new CompanionService(database.connection, audit, () => true), close: () => database.close() }; }
function identity() { return generateKeyPairSync('ed25519'); }
async function pair(service: CompanionService, name = 'Test phone') { const keys = identity(); const challenge = await service.createPairingChallenge(); const signed = `${challenge.challengeId}:${challenge.code}:${name}:ANDROID:phone`; const input = { challengeId: challenge.challengeId, code: challenge.code, name, platform: 'ANDROID' as const, deviceType: 'phone', publicKey: keys.publicKey.export({ type: 'spki', format: 'pem' }).toString(), signature: sign(null, Buffer.from(signed), keys.privateKey).toString('base64') }; return { device: await service.pair(input), keys }; }
function command(deviceId: string, sessionId: string, requestId = `request-${Math.random()}`): CompanionMessage<{ sessionId: string; command: string }> { return { messageId: `message-${requestId}`, deviceId, type: 'COMMAND_REQUEST', timestamp: new Date().toISOString(), requestId, payload: { sessionId, command: 'FILE_READ' } }; }

describe('CompanionService', () => {
  it('pairs with a signed short-lived challenge and stores no private key', async () => { const { service, close } = setup(); const { device, keys } = await pair(service); expect(device.status).toBe('PAIRED'); expect(device.permissions).toEqual(['COMPANION_VIEW_STATUS']); expect(device.publicKey).not.toContain(keys.privateKey.export({ format: 'pem', type: 'pkcs8' }).toString()); close(); });
  it('rejects duplicate devices and expired challenges', async () => { const { service, close } = setup(); const first = await pair(service); const challenge = await service.createPairingChallenge(); const publicKey = first.keys.publicKey.export({ type: 'spki', format: 'pem' }).toString(); const signed = `${challenge.challengeId}:${challenge.code}:Other:ANDROID:phone`; const input = { challengeId: challenge.challengeId, code: challenge.code, name: 'Other', platform: 'ANDROID' as const, deviceType: 'phone', publicKey, signature: sign(null, Buffer.from(signed), first.keys.privateKey).toString('base64') }; await expect(service.pair(input)).rejects.toThrow('already paired'); vi.useFakeTimers(); const expired = await service.createPairingChallenge(); vi.advanceTimersByTime(121000); const keys = identity(); const value = { ...input, challengeId: expired.challengeId, code: expired.code, publicKey: keys.publicKey.export({ type: 'spki', format: 'pem' }).toString() }; value.signature = sign(null, Buffer.from(`${expired.challengeId}:${expired.code}:Other:ANDROID:phone`), keys.privateKey).toString('base64'); await expect(service.pair(value)).rejects.toThrow('expired'); vi.useRealTimers(); close(); });
  it('rate limits repeated invalid pairing attempts', async () => { const { service, close } = setup(); const challenge = await service.createPairingChallenge(); for (let attempt = 0; attempt < 5; attempt += 1) await expect(service.pair({ challengeId: challenge.challengeId, code: 'WRONG', name: 'Phone', platform: 'ANDROID', deviceType: 'phone', publicKey: 'invalid', signature: 'invalid' })).rejects.toThrow(); await expect(service.pair({ challengeId: challenge.challengeId, code: challenge.code, name: 'Phone', platform: 'ANDROID', deviceType: 'phone', publicKey: 'invalid', signature: 'invalid' })).rejects.toThrow('expired'); close(); });
  it('authenticates signed sessions, rejects replay, and expires sessions', async () => { const { service, close } = setup(); const { device, keys } = await pair(service); const nonce = 'nonce-1'; const messageId = 'auth-message'; const requestId = 'auth-request'; const timestamp = new Date().toISOString(); const payload = { nonce, signature: sign(null, Buffer.from(`${messageId}:${device.id}:${requestId}:${timestamp}:${nonce}`), keys.privateKey).toString('base64') }; const message: CompanionMessage<typeof payload> = { messageId, deviceId: device.id, type: 'AUTH_REQUEST', timestamp, requestId, payload }; const session = service.authenticate(message); expect(session.deviceId).toBe(device.id); expect((await service.getSnapshot()).devices[0]?.status).toBe('CONNECTED'); expect(() => service.authenticate(message)).toThrow('replayed'); vi.useFakeTimers(); vi.advanceTimersByTime(901000); expect(() => service.authorizeCommand(command(device.id, session.sessionId, 'expired-command'))).toThrow('expired'); vi.useRealTimers(); close(); });
  it('denies unauthenticated and revoked commands', async () => { const { service, close } = setup(); const { device } = await pair(service); const unauthenticated = command(device.id, 'missing'); expect(() => service.authorizeCommand(unauthenticated)).toThrow(); await service.revoke(device.id); expect(() => service.authorizeCommand({ ...unauthenticated, requestId: 'revoked-request', messageId: 'revoked-message' })).toThrow('not available'); close(); });
  it('requires the device command capability and denies sensitive commands', async () => { const { service, close } = setup(); const { device, keys } = await pair(service); await service.grantPermission(device.id, 'COMPANION_SEND_COMMAND'); const nonce = 'nonce-2'; const messageId = 'auth-message-2'; const requestId = 'auth-request-2'; const timestamp = new Date().toISOString(); const payload = { nonce, signature: sign(null, Buffer.from(`${messageId}:${device.id}:${requestId}:${timestamp}:${nonce}`), keys.privateKey).toString('base64') }; const session = service.authenticate({ messageId, deviceId: device.id, type: 'AUTH_REQUEST', timestamp, requestId, payload }); const allowed = command(device.id, session.sessionId, 'command-allowed'); service.authorizeCommand(allowed); const sensitive = { ...allowed, messageId: 'sensitive-message', requestId: 'sensitive-request', payload: { ...allowed.payload, command: 'FILE_DELETE' } }; expect(() => service.authorizeCommand(sensitive)).toThrow('not authorized'); close(); });
  it('delegates an authorized command and returns a typed response', async () => { const { service, close } = setup(); const { device, keys } = await pair(service); await service.grantPermission(device.id, 'COMPANION_SEND_COMMAND'); const nonce = 'nonce-3'; const messageId = 'auth-message-3'; const requestId = 'auth-request-3'; const timestamp = new Date().toISOString(); const payload = { nonce, signature: sign(null, Buffer.from(`${messageId}:${device.id}:${requestId}:${timestamp}:${nonce}`), keys.privateKey).toString('base64') }; const session = service.authenticate({ messageId, deviceId: device.id, type: 'AUTH_REQUEST', timestamp, requestId, payload }); const request = { ...command(device.id, session.sessionId, 'command-delegated'), payload: { sessionId: session.sessionId, command: 'FILE_READ', input: { path: 'README.md' } } }; const response = await service.handleCommand(request, async (commandName, input) => ({ commandName, input })); expect(response.type).toBe('COMMAND_RESPONSE'); expect(response.payload.result).toEqual({ commandName: 'FILE_READ', input: { path: 'README.md' } }); close(); });
  it('rejects malformed and unknown message types and supports offline operation', async () => { const { service, close } = setup(); expect(() => service.validateIncoming({} as CompanionMessage)).toThrow('malformed'); expect(() => service.validateIncoming({ messageId: 'm', deviceId: 'x', type: 'UNKNOWN', timestamp: new Date().toISOString(), requestId: 'r', payload: {} } as never)).toThrow('malformed'); expect((await service.getSnapshot()).connectionState).toBe('OFFLINE'); close(); });
});
