import { createHash, createPublicKey, randomBytes, randomUUID, verify } from 'node:crypto';
import type Database from 'better-sqlite3';
import type { AuditService } from '../auditService';
import type { CompanionBridge, CompanionDevice, CompanionMessage, CompanionPermission, CompanionSession, PairInput, PairingChallenge } from '../../shared/companionTypes';
import { LocalDevelopmentTransport, type CompanionTransport } from './companionTransport';
const PAIRING_MS=2*60*1000,SESSION_MS=15*60*1000,MAX_ATTEMPTS=5; const SENSITIVE=new Set(['FILE_DELETE','MESSAGE_SEND','PERMISSION_CHANGE','ACCOUNT_ACCESS','DEVICE_CONTROL']);
export class CompanionService implements CompanionBridge{
 private readonly challenges=new Map<string,{challenge:PairingChallenge;attempts:number}>();private readonly sessions=new Map<string,CompanionSession>();private readonly replayed=new Set<string>();private readonly devices=new Map<string,CompanionDevice>();private readonly transport:CompanionTransport;private pairing?:PairingChallenge;
 constructor(private readonly connection:Database.Database,private readonly audit:AuditService,private readonly authorizeDesktopCommand:(command:string)=>boolean=()=>false,transport:CompanionTransport=new LocalDevelopmentTransport()){this.transport=transport;this.load();}
 async getSnapshot(){return{devices:[...this.devices.values()].map(d=>({...d,permissions:[...d.permissions]})),pairing:this.pairing,connectionState:this.transport.state};}
 async createPairingChallenge():Promise<PairingChallenge>{if(this.pairing){const existing=this.challenges.get(this.pairing.challengeId);if(existing&&Date.parse(existing.challenge.expiresAt)>Date.now())return existing.challenge;}const challenge={challengeId:randomUUID(),code:randomBytes(4).toString('hex').toUpperCase(),expiresAt:new Date(Date.now()+PAIRING_MS).toISOString()};this.challenges.set(challenge.challengeId,{challenge,attempts:0});this.pairing=challenge;this.audit.record('COMPANION_PAIR_REQUESTED');return challenge;}
 async pair(input:PairInput):Promise<CompanionDevice>{const record=this.challenges.get(input.challengeId);if(!record)throw new Error('Pairing challenge is invalid or expired.');record.attempts+=1;if(record.attempts>MAX_ATTEMPTS||Date.parse(record.challenge.expiresAt)<=Date.now()||record.challenge.code!==input.code)throw new Error('Pairing challenge is invalid or expired.');const signed=`${input.challengeId}:${input.code}:${input.name}:${input.platform}:${input.deviceType}`;if(!verify(null,Buffer.from(signed),this.publicKey(input.publicKey),Buffer.from(input.signature,'base64')))throw new Error('Pairing authentication failed.');if([...this.devices.values()].some(d=>d.publicKey===input.publicKey&&d.status!=='REVOKED'))throw new Error('Device is already paired.');const now=new Date().toISOString();const device:CompanionDevice={id:randomUUID(),name:input.name.trim().slice(0,80),platform:input.platform,deviceType:input.deviceType.trim().slice(0,80),publicKey:input.publicKey,status:'PAIRED',createdAt:now,lastSeenAt:now,permissions:['COMPANION_VIEW_STATUS']};this.devices.set(device.id,device);this.save(device);this.challenges.delete(input.challengeId);if(this.pairing?.challengeId===input.challengeId)this.pairing=undefined;this.audit.record('COMPANION_PAIRED',device.id);return{...device,permissions:[...device.permissions]};}
 authenticate(message:CompanionMessage<{nonce:string;signature:string}>):CompanionSession{const device=this.requireDevice(message.deviceId);this.checkMessage(message);const signed=`${message.messageId}:${message.deviceId}:${message.requestId}:${message.timestamp}:${message.payload.nonce}`;if(!verify(null,Buffer.from(signed),this.publicKey(device.publicKey),Buffer.from(message.payload.signature,'base64'))){this.audit.record('COMPANION_AUTH_FAILED',device.id);throw new Error('Companion authentication failed.');}const session={sessionId:randomUUID(),deviceId:device.id,expiresAt:new Date(Date.now()+SESSION_MS).toISOString()};this.sessions.set(session.sessionId,session);device.status='CONNECTED';device.lastSeenAt=new Date().toISOString();this.save(device);this.audit.record('COMPANION_AUTHENTICATED',device.id);this.audit.record('COMPANION_CONNECTED',device.id);return session;}
 async disconnect(deviceId:string){const device=this.requireDevice(deviceId);device.status='DISCONNECTED';this.save(device);for(const[id,s]of this.sessions)if(s.deviceId===deviceId)this.sessions.delete(id);this.audit.record('COMPANION_DISCONNECTED',deviceId);await this.transport.disconnect();}
 async revoke(deviceId:string){const device=this.requireDevice(deviceId);device.status='REVOKED';device.revokedAt=new Date().toISOString();this.save(device);for(const[id,s]of this.sessions)if(s.deviceId===deviceId)this.sessions.delete(id);this.audit.record('COMPANION_REVOKED',deviceId);}
 async grantPermission(deviceId:string,permission:CompanionPermission):Promise<CompanionDevice>{const device=this.requireDevice(deviceId);if(!device.permissions.includes(permission))device.permissions.push(permission);this.save(device);return{...device,permissions:[...device.permissions]};}
 validateIncoming(message:CompanionMessage):void{this.checkMessage(message);this.requireDevice(message.deviceId);}
 authorizeSync(message:CompanionMessage<{sessionId:string}>,permission:CompanionPermission):void{const device=this.requireDevice(message.deviceId);this.checkMessage(message);const session=this.sessions.get(message.payload.sessionId);if(!session||session.deviceId!==device.id||Date.parse(session.expiresAt)<=Date.now())throw new Error('Companion session is expired.');if(!device.permissions.includes(permission))throw new Error('Companion permission is not authorized.');}
 authorizeCommand(message:CompanionMessage<{sessionId:string;command:string}>):void{const device=this.requireDevice(message.deviceId);this.checkMessage(message);const session=this.sessions.get(message.payload.sessionId);if(!session||session.deviceId!==device.id||Date.parse(session.expiresAt)<=Date.now())throw new Error('Companion session is expired.');if(!device.permissions.includes('COMPANION_SEND_COMMAND')||SENSITIVE.has(message.payload.command)||!this.authorizeDesktopCommand(message.payload.command))throw new Error('Companion command is not authorized.');this.audit.record('COMPANION_COMMAND_REQUESTED',device.id);}
 async handleCommand<T>(message:CompanionMessage<{sessionId:string;command:string;input:T}>,execute:(command:string,input:T)=>Promise<unknown>):Promise<CompanionMessage<{result:unknown}>>{this.authorizeCommand(message);const result=await execute(message.payload.command,message.payload.input);return{messageId:randomUUID(),deviceId:message.deviceId,type:'COMMAND_RESPONSE',timestamp:new Date().toISOString(),requestId:message.requestId,payload:{result}};}
 private checkMessage(message:CompanionMessage):void{if(!message.messageId||!message.requestId||!message.deviceId||!message.timestamp||!message.type||!message.payload)throw new Error('Companion message is malformed.');if(Math.abs(Date.now()-Date.parse(message.timestamp))>5*60*1000||this.replayed.has(message.requestId))throw new Error('Companion request is expired or replayed.');this.replayed.add(message.requestId);if(this.replayed.size>1000)this.replayed.delete(this.replayed.values().next().value as string);}
 private requireDevice(id:string):CompanionDevice{const device=this.devices.get(id);if(!device||device.status==='REVOKED')throw new Error('Companion device is not available.');return device;}
 private publicKey(value:string):ReturnType<typeof createPublicKey>{if(value.includes('BEGIN'))return createPublicKey(value);const raw=Buffer.from(value.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-value.length%4)%4),'base64');if(raw.length!==32)throw new Error('Companion public key is invalid.');return createPublicKey({key:Buffer.concat([Buffer.from('302a300506032b6570032100','hex'),raw]),format:'der',type:'spki'});}
 private load():void{const rows=this.connection.prepare('SELECT id,name,platform,device_type as deviceType,public_key as publicKey,status,created_at as createdAt,last_seen_at as lastSeenAt,permissions_json as permissions,revoked_at as revokedAt FROM companion_devices').all() as Array<CompanionDevice&{permissions:string}>;rows.forEach(row=>this.devices.set(row.id,{...row,permissions:JSON.parse(row.permissions) as CompanionPermission[]}));}
 private save(device:CompanionDevice):void{this.connection.prepare('INSERT OR REPLACE INTO companion_devices (id,name,platform,device_type,public_key,status,created_at,last_seen_at,permissions_json,revoked_at) VALUES (?,?,?,?,?,?,?,?,?,?)').run(device.id,device.name,device.platform,device.deviceType,device.publicKey,device.status,device.createdAt,device.lastSeenAt,JSON.stringify(device.permissions),device.revokedAt);}
}
export function fingerprintPublicKey(publicKey:string):string{return createHash('sha256').update(publicKey).digest('hex').slice(0,16);}
