import { useEffect, useState } from 'react';
import type { ReactElement } from 'react';
import type { RuntimeStatus } from '../../../shared/types';
import type { PermissionGrant } from '../../../shared/permissionTypes';
import type { TeshVisualStateController } from '../../hooks/useTeshVisualState';
import { conversationTimeoutOptions, writeConversationTimeout, type ConversationTimeoutSeconds } from '../../services/conversationTimeout';
import { VoiceEnrollmentPanel } from '../voice/VoiceEnrollmentPanel';

const sections = ['GENERAL', 'VOICE & WAKE', 'AI', 'PERMISSIONS', 'FILES', 'COMPANION', 'PRIVACY', 'ABOUT'] as const;
type Section = (typeof sections)[number];
interface SettingsProps { voice: TeshVisualStateController['voice']; snapshot: TeshVisualStateController['voiceSnapshot']; runtimeStatus?: RuntimeStatus; conversationTimeout: ConversationTimeoutSeconds; onConversationTimeoutChange: (value: ConversationTimeoutSeconds) => void; }

export function SettingsPanel({ voice, snapshot, runtimeStatus, conversationTimeout, onConversationTimeoutChange }: SettingsProps): ReactElement {
  const [section, setSection] = useState<Section>('GENERAL');
  const [permissions, setPermissions] = useState<PermissionGrant[]>([]);
  const [ai, setAi] = useState({ configured: false, provider: 'unavailable', model: 'unavailable' });
  const [companion, setCompanion] = useState<{ devices: Array<{ name: string; status: string; revokedAt?: string }>; connectionState: string }>();
  const [microphonePermission, setMicrophonePermission] = useState('UNKNOWN');
  const [completed, setCompleted] = useState(() => localStorage.getItem('tesh.setup.completed') === 'true');
  const nativeVoiceEnabled = !import.meta.env.DEV || import.meta.env.VITE_TESH_NATIVE_VOICE === 'true';
  const refresh = async (): Promise<void> => { const [grants, status, companionSnapshot, microphoneState] = await Promise.all([window.tesh?.permissions.listPermissions() ?? [], window.tesh?.conversation.getStatus() ?? Promise.resolve({ configured: false, provider: 'unavailable', model: 'unavailable' }), window.tesh?.companion?.getSnapshot() ?? Promise.resolve(undefined), window.tesh?.permissions.check('MICROPHONE') ?? Promise.resolve('UNKNOWN')]); setPermissions(grants); setAi(status); setCompanion(companionSnapshot); setMicrophonePermission(microphoneState); };
  useEffect(() => { void refresh(); }, [snapshot.microphone]);
  useEffect(() => () => { void voice.stopMicrophoneTest(); }, [voice, section]);
  const saveTimeout = (value: string): void => { try { onConversationTimeoutChange(writeConversationTimeout(Number(value))); } catch { /* select options are constrained */ } };
  const completeSetup = (): void => { localStorage.setItem('tesh.setup.completed', 'true'); setCompleted(true); };
  const capability = (name: string): string => name === 'AI' ? (ai.configured ? 'CONFIGURED' : 'NOT CONFIGURED') : name === 'Companion' ? (companion?.devices.length ? 'CONNECTED' : 'DISCONNECTED') : name === 'Microphone' ? (microphonePermission === 'GRANTED' ? 'READY' : 'PERMISSION REQUIRED') : name === 'Wake Word' ? (nativeVoiceEnabled ? 'Tesh' : 'DEVELOPMENT ONLY') : name === 'Speaker Verification' ? (nativeVoiceEnabled ? 'CONFIGURED BY SETUP' : 'DEVELOPMENT ONLY') : 'DEVELOPMENT ONLY';
  return <section className="settings-panel" aria-label="Tesh settings"><nav className="settings-nav">{sections.map((item) => <button className={section === item ? 'active' : ''} key={item} type="button" onClick={() => setSection(item)}>{item}</button>)}</nav><div className="settings-content"><p className="panel-label">Settings / {section}</p>
    {section === 'GENERAL' && <><h2>Tesh status</h2><p className="settings-lead">Tesh runs in the tray and only reveals the assistant after voice activation succeeds.</p><CapabilityGrid names={['Voice', 'Speech Recognition', 'Wake Word', 'Speaker Verification', 'AI', 'Memory', 'Filesystem', 'Companion']} status={capability} /><div className="settings-readout"><Readout label="Start with Windows" value="Unavailable" /><Readout label="Start in background" value="Enabled" /><Readout label="Notifications" value="Unavailable" /><Readout label="Version" value={runtimeStatus?.appVersion ?? 'Unavailable'} /><Readout label="Build" value={runtimeStatus?.isPackaged ? 'Packaged' : 'Development'} /></div><button type="button" onClick={completeSetup}>{completed ? 'Setup completed' : 'Finish setup'}</button></>}
    {section === 'VOICE & WAKE' && <><h2>Voice &amp; Wake</h2><CapabilityGrid names={['Microphone', 'Speech Recognition', 'Wake Word', 'Speaker Verification', 'Voice Activation']} status={capability} />{nativeVoiceEnabled ? <VoiceEnrollmentPanel /> : <p className="settings-lead">Enable the native voice path to configure real voice enrollment. Development mock verification remains available in the development panel.</p>}<MicrophoneTest voice={voice} snapshot={snapshot} /><TimeoutSetting value={conversationTimeout} onChange={saveTimeout} /></>}
    {section === 'AI' && <><h2>AI</h2><article className="capability-status"><strong>{ai.configured ? ai.provider : 'AI'}</strong><span>{capability('AI')}</span><p>{ai.configured ? `Model ${ai.model}. Credentials remain isolated in the main process.` : 'AI is not configured.'}</p></article></>}
    {section === 'PERMISSIONS' && <><h2>Permissions</h2><p className="settings-lead">Actual records from the existing authorization service.</p>{permissions.length ? permissions.map((item) => <article className="permission-item" key={item.id}><strong>{item.permission} · {item.state}</strong><span>{item.scope || 'Global'} · {item.duration} · {item.expiresAt ? new Date(item.expiresAt).toLocaleString() : 'no expiration'}</span><button type="button" onClick={() => void window.tesh?.permissions.revoke(item.id).then(refresh)}>Revoke</button></article>) : <p className="settings-lead">No permission records.</p>}</>}
    {section === 'FILES' && <StatusSection title="Files" state="PERMISSION REQUIRED" detail="Filesystem access remains scope-validated and permission-authorized. No arbitrary folders are exposed." />}
    {section === 'COMPANION' && <><h2>Companion</h2>{companion?.devices.length ? companion.devices.map((device) => <article className="capability-status" key={device.name}><strong>{device.name}</strong><span>{device.status} · {companion.connectionState}</span><p>{device.revokedAt ? 'REVOKED' : 'TLS companion device.'}</p></article>) : <p className="settings-lead">No companion devices paired.</p>}</>}
    {section === 'PRIVACY' && <><h2>Privacy</h2><p className="settings-lead">Microphone audio is captured only while listening or enrolling; raw recordings are not permanently stored by the Tesh enrollment flow. Other data remains governed by the existing local services and permission boundaries.</p><CapabilityGrid names={['Microphone', 'Voice activation', 'Speaker verification', 'Memory', 'Conversation storage', 'Filesystem', 'Companion']} status={capability} /></>}
    {section === 'ABOUT' && <><h2>About Tesh</h2><div className="settings-readout"><Readout label="Version" value={runtimeStatus?.appVersion ?? 'Unavailable'} /><Readout label="Electron" value={runtimeStatus ? 'Electron runtime' : 'Unavailable'} /><Readout label="Operating system" value={runtimeStatus?.platform ?? 'Unavailable'} /><Readout label="Environment" value={runtimeStatus?.isPackaged ? 'Production' : 'Development'} /><Readout label="Security" value="Isolated preload" /></div></>}
    {!completed && section !== 'GENERAL' ? <button type="button" onClick={completeSetup}>Finish first-run setup</button> : null}</div></section>;
}
function CapabilityGrid({ names, status }: { names: string[]; status: (name: string) => string }): ReactElement { return <div className="capability-grid">{names.map((name) => <article className="capability-status" key={name}><strong>{name}</strong><span>{status(name)}</span><p>{name === 'AI' ? 'Provider configuration is kept in the main process.' : name === 'Wake Word' ? 'Wake phrase: Tesh.' : name === 'Speaker Verification' ? 'Voice identity is established during enrollment.' : 'Status reported by the existing service.'}</p></article>)}</div>; }
function Readout({ label, value }: { label: string; value: string }): ReactElement { return <div><span className="panel-label">{label}</span><strong>{value}</strong></div>; }
function StatusSection({ title, state, detail }: { title: string; state: string; detail: string }): ReactElement { return <><h2>{title}</h2><article className="capability-status"><strong>{title}</strong><span>{state}</span><p>{detail}</p></article></>; }
function TimeoutSetting({ value, onChange }: { value: ConversationTimeoutSeconds; onChange: (value: string) => void }): ReactElement { return <article className="microphone-test"><div className="settings-heading"><div><span className="panel-label">Conversation</span><h3>Conversation inactivity timeout</h3></div><strong>{value === 0 ? 'Never' : `${value / 60} min`}</strong></div><p className="settings-lead">How long Tesh stays available after you stop speaking.</p><select value={value} onChange={(event) => onChange(event.target.value)} aria-label="Conversation inactivity timeout">{conversationTimeoutOptions.map((seconds) => <option key={seconds} value={seconds}>{seconds === 0 ? 'Never' : seconds < 60 ? `${seconds} seconds` : `${seconds / 60} minute${seconds === 60 ? '' : 's'}`}</option>)}</select></article>; }
function MicrophoneTest({ voice, snapshot }: { voice: TeshVisualStateController['voice']; snapshot: TeshVisualStateController['voiceSnapshot'] }): ReactElement { const [message, setMessage] = useState(''); const start = async (): Promise<void> => { try { const bridge = window.tesh?.permissions; if (!bridge) throw new Error('Microphone controls are unavailable in browser preview.'); if ((await bridge.check('MICROPHONE')) !== 'GRANTED') await bridge.grant('MICROPHONE', undefined, 'SESSION'); await voice.startMicrophoneTest(); setMessage(''); } catch (error) { setMessage(error instanceof Error ? error.message : 'Microphone access is required for this test.'); } }; return <article className="microphone-test" aria-label="Microphone test"><div className="settings-heading"><div><span className="panel-label">Microphone</span><h3>Test microphone</h3></div><strong>{snapshot.microphoneTest ? 'LISTENING' : snapshot.microphone.toUpperCase()}</strong></div><div className="amplitude-meter" role="meter" aria-label="Microphone amplitude" aria-valuemin={0} aria-valuemax={1} aria-valuenow={snapshot.audio.amplitude}><span style={{ width: `${Math.round(snapshot.audio.amplitude * 100)}%` }} /></div><div className="voice-actions"><button type="button" onClick={() => void start()} disabled={snapshot.microphoneTest}>Test Microphone</button><button type="button" onClick={() => void voice.stopMicrophoneTest()} disabled={!snapshot.microphoneTest}>Stop Test</button></div><p className="memory-message">{message || snapshot.error?.message}</p></article>; }
