import { afterEach, describe, expect, it, vi } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { initializeMemoryDatabase } from '../memory/memoryDatabase';
import { PermissionRepository } from '../permissions/permissionRepository';
import { PermissionService } from '../permissions/permissionService';
import { CommunicationService } from './communicationService';
import { MockCommunicationProvider } from './mockCommunicationProvider';

describe('CommunicationService', () => {
  const paths: string[] = [];
  afterEach(() => { paths.splice(0).forEach((file) => { for (const suffix of ['', '-shm', '-wal']) { try { fs.unlinkSync(file + suffix); } catch { } } }); });
  function setup(verified = true) { const databasePath = path.join(os.tmpdir(), `tesh-communication-${Date.now()}-${Math.random()}.sqlite`); paths.push(databasePath); const database = initializeMemoryDatabase(databasePath); const permissions = new PermissionService(new PermissionRepository(database.connection)); const provider = new MockCommunicationProvider(); const service = new CommunicationService(provider, permissions, () => verified); return { database, permissions, provider, service }; }

  it('resolves exact, ambiguous, and missing recipients without guessing', async () => { const { database, service } = setup(); expect((await service.resolveRecipient('Jordan')).status).toBe('EXACT_MATCH'); expect((await service.resolveRecipient('Sarah')).status).toBe('MULTIPLE_MATCHES'); expect((await service.resolveRecipient('Nobody')).status).toBe('NO_MATCH'); database.close(); });
  it('creates a draft but never sends without explicit current confirmation', async () => { const { database, permissions, service, provider } = setup(); permissions.grantPermission('COMMUNICATE', undefined, 'SESSION'); const draft = await service.createDraft({ recipientQuery: 'Jordan', content: 'Hello Jordan.' }); expect(draft.status).toBe('AWAITING_CONFIRMATION'); expect(provider.sent).toHaveLength(0); const cancelled = await service.cancelDraft(draft.id); expect(cancelled.status).toBe('CANCELLED'); expect(provider.sent).toHaveLength(0); database.close(); });
  it('invalidates approval when a draft changes', async () => { const { database, permissions, service, provider } = setup(); permissions.grantPermission('COMMUNICATE', undefined, 'SESSION'); const draft = await service.createDraft({ recipientQuery: 'Jordan', content: 'First version.' }); const edited = await service.updateDraft(draft.id, 'Second version.'); expect(edited.status).toBe('AWAITING_CONFIRMATION'); const sent = await service.confirmSend(edited.id, true); expect(sent.status).toBe('SENT'); expect(provider.sent[0]?.content).toBe('Second version.'); database.close(); });
  it('requires both a verified session and communication permission', async () => { const missingPermission = setup(); const failedDraft = await missingPermission.service.createDraft({ recipientQuery: 'Jordan', content: 'Hello.' }); expect(failedDraft.status).toBe('FAILED'); expect((await missingPermission.service.confirmSend(failedDraft.id, true)).status).toBe('FAILED'); missingPermission.database.close(); const missingSession = setup(false); missingSession.permissions.grantPermission('COMMUNICATE', undefined, 'SESSION'); const draft = await missingSession.service.createDraft({ recipientQuery: 'Jordan', content: 'Hello.' }); expect(draft.status).toBe('AWAITING_CONFIRMATION'); expect((await missingSession.service.confirmSend(draft.id, true)).status).toBe('FAILED'); expect(missingSession.provider.sent).toHaveLength(0); missingSession.database.close(); });
  it('sends only after explicit confirmation and records no credentials', async () => { const { database, permissions, service, provider } = setup(); permissions.grantPermission('COMMUNICATE', undefined, 'SESSION'); const draft = await service.createDraft({ recipientQuery: 'Jordan', content: 'Confirmed.' }); const sent = await service.confirmSend(draft.id, true); expect(sent.status).toBe('SENT'); expect(provider.sent).toHaveLength(1); expect(JSON.stringify(sent)).not.toMatch(/password|token|cookie|secret/i); database.close(); });
  it('prevents concurrent confirmations from sending twice', async () => { const { database, permissions, service, provider } = setup(); permissions.grantPermission('COMMUNICATE', undefined, 'SESSION'); let release: (() => void) | undefined; provider.sendMessage = async (recipient, content) => { await new Promise<void>((resolve) => { release = resolve; }); provider.sent.push({ recipient, content }); }; const draft = await service.createDraft({ recipientQuery: 'Jordan', content: 'Only once.' }); const first = service.confirmSend(draft.id, true); const second = service.confirmSend(draft.id, true); await vi.waitFor(() => expect(provider.sent).toHaveLength(0)); release?.(); await Promise.all([first, second]); expect(provider.sent).toHaveLength(1); database.close(); });
});