import { randomUUID } from 'node:crypto';
import type { CommunicationBridge, CommunicationProviderKind, CommunicationSnapshot, Contact, CreateDraftInput, MessageDraft, RecipientResolution, RecipientResolutionStatus } from '../../shared/communicationTypes';
import type { PermissionService } from '../permissions/permissionService';
import type { CommunicationProvider } from '../../shared/communicationTypes';

type AuditEvent = 'CONTACT_RESOLUTION_REQUESTED' | 'CONTACT_RESOLVED' | 'MESSAGE_DRAFT_CREATED' | 'MESSAGE_DRAFT_UPDATED' | 'MESSAGE_CONFIRMATION_REQUESTED' | 'MESSAGE_CONFIRMED' | 'MESSAGE_CANCELLED' | 'MESSAGE_SEND_REQUESTED' | 'MESSAGE_SENT' | 'MESSAGE_SEND_FAILED';

export class CommunicationService implements CommunicationBridge {
  private readonly drafts = new Map<string, MessageDraft>();
  private readonly sending = new Set<string>();
  private readonly history: Array<{ recipientId: string; provider: CommunicationProviderKind; timestamp: string; status: string; authorizationResult: string; confirmationResult: string }> = [];
  private snapshot: CommunicationSnapshot = { provider: 'MOCK', contacts: [] };
  constructor(private readonly provider: CommunicationProvider, private readonly permissions: PermissionService, private readonly isVerified: () => boolean, private readonly audit: (event: AuditEvent) => void = () => undefined) {}
  async getContacts(): Promise<Contact[]> { const contacts = await this.provider.getContacts(); this.snapshot = { ...this.snapshot, contacts }; return contacts; }
  async resolveRecipient(query: string): Promise<RecipientResolution> { this.audit('CONTACT_RESOLUTION_REQUESTED'); const contacts = this.snapshot.contacts.length ? this.snapshot.contacts : await this.getContacts(); const normalized = query.trim().toLowerCase(); const matches = contacts.filter((contact) => contact.displayName.toLowerCase() === normalized || contact.displayName.toLowerCase().startsWith(normalized) || contact.displayName.toLowerCase().includes(normalized)); const status: RecipientResolutionStatus = matches.length === 1 ? 'EXACT_MATCH' : matches.length > 1 ? 'MULTIPLE_MATCHES' : 'NO_MATCH'; const resolution: RecipientResolution = { status, query, matches }; this.snapshot = { ...this.snapshot, resolution }; this.audit('CONTACT_RESOLVED'); return resolution; }
  async createDraft(input: CreateDraftInput): Promise<MessageDraft> { if (!input.content.trim() || input.content.length > 10000) throw new Error('Draft content is invalid.'); const resolution = await this.resolveRecipient(input.recipientQuery); const recipient = input.contactId ? resolution.matches.find((contact) => contact.id === input.contactId) : resolution.matches.length === 1 ? resolution.matches[0] : undefined; if (!recipient) throw new Error(resolution.status === 'MULTIPLE_MATCHES' ? 'Recipient is ambiguous.' : 'Recipient was not found.'); const authorization = this.authorize(); const draft: MessageDraft = { id: randomUUID(), recipient, provider: this.provider.kind, content: input.content.trim(), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), styleProfileUsed: input.styleProfileUsed, status: authorization === 'ALLOWED' ? 'AWAITING_CONFIRMATION' : 'FAILED', authorizationResult: authorization, confirmationRequired: true }; this.drafts.set(draft.id, draft); this.snapshot = { ...this.snapshot, draft }; this.audit('MESSAGE_DRAFT_CREATED'); this.audit('MESSAGE_CONFIRMATION_REQUESTED'); return { ...draft }; }
  async updateDraft(id: string, content: string): Promise<MessageDraft> { const draft = this.getDraft(id); if (!content.trim() || content.length > 10000) throw new Error('Draft content is invalid.'); const updated = { ...draft, content: content.trim(), updatedAt: new Date().toISOString(), status: 'AWAITING_CONFIRMATION' as const, confirmationRequired: true }; this.drafts.set(id, updated); this.snapshot = { ...this.snapshot, draft: updated }; this.audit('MESSAGE_DRAFT_UPDATED'); this.audit('MESSAGE_CONFIRMATION_REQUESTED'); return { ...updated }; }
  async confirmSend(id: string, approved: boolean): Promise<MessageDraft> { const draft = this.getDraft(id); if (!approved) return this.cancelDraft(id); if (this.sending.has(id)) return { ...draft }; if (draft.status !== 'AWAITING_CONFIRMATION' || !this.isVerified() || this.authorize() !== 'ALLOWED') return this.fail(draft, 'Send authorization is not available.'); this.sending.add(id); this.audit('MESSAGE_CONFIRMED'); this.audit('MESSAGE_SEND_REQUESTED'); try { await this.provider.sendMessage(draft.recipient, draft.content); const sent = { ...draft, status: 'SENT' as const, confirmationRequired: false, updatedAt: new Date().toISOString() }; this.drafts.set(id, sent); this.history.push({ recipientId: draft.recipient.id, provider: draft.provider, timestamp: sent.updatedAt, status: sent.status, authorizationResult: sent.authorizationResult, confirmationResult: 'APPROVED' }); this.audit('MESSAGE_SENT'); this.snapshot = { ...this.snapshot, draft: sent, sendResult: 'Message sent by development mock provider.' }; return { ...sent }; } catch { return this.fail(draft, 'Communication provider failed.'); } finally { this.sending.delete(id); } }
  async cancelDraft(id: string): Promise<MessageDraft> { const draft = this.getDraft(id); const cancelled = { ...draft, status: 'CANCELLED' as const, confirmationRequired: false, updatedAt: new Date().toISOString() }; this.drafts.set(id, cancelled); this.audit('MESSAGE_CANCELLED'); this.snapshot = { ...this.snapshot, draft: cancelled }; return { ...cancelled }; }
  async getSnapshot(): Promise<CommunicationSnapshot> { if (!this.snapshot.contacts.length) await this.getContacts(); return { ...this.snapshot, draft: this.snapshot.draft ? { ...this.snapshot.draft } : undefined, contacts: this.snapshot.contacts.map((contact) => ({ ...contact })) }; }
  getHistory(): readonly CommunicationService['history'][number][] { return [...this.history]; }
  private authorize(): string { const result = this.permissions.authorizeAction({ capabilityId: 'message.send', resource: 'communication', confirmed: true }); return result.result === 'ALLOWED' ? 'ALLOWED' : result.result; }
  private getDraft(id: string): MessageDraft { const draft = this.drafts.get(id); if (!draft) throw new Error('Message draft was not found.'); return draft; }
  private fail(draft: MessageDraft, reason: string): MessageDraft { const failed = { ...draft, status: 'FAILED' as const, confirmationRequired: true }; this.drafts.set(draft.id, failed); this.audit('MESSAGE_SEND_FAILED'); this.snapshot = { ...this.snapshot, draft: failed, lastError: reason }; return { ...failed }; }
}