import { useEffect, useState } from 'react';
import type { ReactElement } from 'react';
import type { CompanionPermission, CompanionDevice } from '../../../shared/companionTypes';
import type { PermissionGrant } from '../../../shared/permissionTypes';

const companionPermissions: CompanionPermission[] = ['COMPANION_VIEW_STATUS','COMPANION_CHAT','COMPANION_SYNC_MEMORY','COMPANION_SYNC_CONVERSATIONS','COMPANION_SYNC_ROUTINES','COMPANION_RECEIVE_NOTIFICATIONS','COMPANION_SEND_COMMAND'];
const labels: Record<CompanionPermission,string> = { COMPANION_VIEW_STATUS:'Status', COMPANION_CHAT:'Chat', COMPANION_SYNC_MEMORY:'Memory', COMPANION_SYNC_CONVERSATIONS:'Conversations', COMPANION_SYNC_ROUTINES:'Routines', COMPANION_RECEIVE_NOTIFICATIONS:'Notifications', COMPANION_SEND_COMMAND:'Desktop commands' };

export function ControlCenterPanel(): ReactElement {
  const [permissions,setPermissions]=useState<PermissionGrant[]>([]); const [devices,setDevices]=useState<CompanionDevice[]>([]); const [busy,setBusy]=useState(''); const [message,setMessage]=useState('');
  const refresh=async():Promise<void>=>{const bridge=window.tesh;if(!bridge)return;setPermissions(await bridge.permissions.listPermissions());setDevices((await bridge.companion?.getSnapshot())?.devices??[]);};
  useEffect(()=>{void refresh();},[]);
  const grant=async(deviceId:string,permission:CompanionPermission):Promise<void>=>{if(!window.tesh?.companion)return;setBusy(`${deviceId}:${permission}`);try{await window.tesh.companion.grantPermission(deviceId,permission);setMessage(`${labels[permission]} access granted.`);await refresh();}catch(error){setMessage(error instanceof Error?error.message:'Permission update failed.')}finally{setBusy('')}};
  const revokeDevice=async(deviceId:string):Promise<void>=>{if(!window.tesh?.companion)return;setBusy(`${deviceId}:revoke`);try{await window.tesh.companion.revoke(deviceId);setMessage('Device revoked.');await refresh();}catch(error){setMessage(error instanceof Error?error.message:'Device revoke failed.')}finally{setBusy('')}};
  const disconnectDevice=async(deviceId:string):Promise<void>=>{if(!window.tesh?.companion)return;setBusy(`${deviceId}:disconnect`);try{await window.tesh.companion.disconnect(deviceId);setMessage('Device disconnected.');await refresh();}catch(error){setMessage(error instanceof Error?error.message:'Device disconnect failed.')}finally{setBusy('')}};
  const revoke=async(permissionId:string):Promise<void>=>{try{await window.tesh?.permissions.revoke(permissionId);setMessage('Permission revoked.');await refresh();}catch(error){setMessage(error instanceof Error?error.message:'Permission revoke failed.')}};
  return <section className="control-center" aria-label="Tesh control center"><div className="control-center-header"><div><span className="panel-label">TESH CONTROL CENTER</span><h2>Devices &amp; access</h2><p className="settings-lead">Manage local permissions and trusted companion devices.</p></div><button type="button" onClick={()=>void refresh()}>Refresh</button></div><div className="control-grid"><article className="capability-status"><strong>Desktop permissions</strong><span>{permissions.length} configured</span><p>Local capabilities remain independently revocable.</p></article><article className="capability-status"><strong>Trusted devices</strong><span>{devices.filter(d=>d.status==='CONNECTED').length} connected / {devices.length} paired</span><p>New companion devices begin with status-only access.</p></article></div><div className="device-list">{devices.map(device=><article className="permission-item" key={device.id}><strong>{device.name}</strong><span>{device.platform} · {device.status}</span><div className="voice-actions">{companionPermissions.map(permission=><button key={permission} type="button" disabled={busy===`${device.id}:${permission}`||device.status==='REVOKED'||device.permissions.includes(permission)} onClick={()=>void grant(device.id,permission)}>{device.permissions.includes(permission)?`${labels[permission]} ✓`:labels[permission]}</button>)}</div><div className="voice-actions"><button type="button" disabled={busy===`${device.id}:disconnect`||device.status==='REVOKED'} onClick={()=>void disconnectDevice(device.id)}>Disconnect</button><button type="button" disabled={busy===`${device.id}:revoke`||device.status==='REVOKED'} onClick={()=>void revokeDevice(device.id)}>Revoke device</button></div></article>)}{devices.length===0?<p className="settings-lead">No companion devices paired.</p>:null}</div><div className="device-list">{permissions.map(permission=><article className="permission-item" key={permission.id}><strong>{permission.permission}</strong><span>{permission.scope||'Global'} · {permission.duration}</span><button type="button" onClick={()=>void revoke(permission.id)}>Revoke</button></article>)}</div><p className="memory-message" aria-live="polite">{message}</p></section>;
}
