import { randomUUID } from 'node:crypto';
import type Database from 'better-sqlite3';
import type { CommunicationStyleProfile, ConversationPrivacy, Memory, MemoryCandidate, MemoryCandidateInput, MemoryIntelligenceBridge } from '../../shared/memoryTypes';
import type { PermissionService } from '../permissions/permissionService';
import type { MemoryService } from './memoryService';

const sensitive = /(password|passcode|api[_ -]?key|secret|token|private key|authentication code|credit card|bank account|biometric|medical|precise location)/i;
const candidateColumns = 'id, content, category, importance, source, source_conversation_id, source_message_id, confidence, reason, status, created_at';
interface CandidateRow { id: string; content: string; category: MemoryCandidate['category']; importance: MemoryCandidate['importance']; source: MemoryCandidate['source']; source_conversation_id: string | null; source_message_id: string | null; confidence: number; reason: string; status: MemoryCandidate['status']; created_at: string; }
function mapCandidate(row: CandidateRow): MemoryCandidate { return { id: row.id, content: row.content, category: row.category, importance: row.importance, source: row.source, sourceConversationId: row.source_conversation_id ?? undefined, sourceMessageId: row.source_message_id ?? undefined, confidence: row.confidence, reason: row.reason, status: row.status, createdAt: row.created_at }; }

export class MemoryIntelligenceService implements MemoryIntelligenceBridge {
  constructor(private readonly database: Database.Database, private readonly memories: MemoryService, private readonly permissions: PermissionService, private readonly onEvent: (event: 'MEMORY_CANDIDATE_CREATED' | 'MEMORY_APPROVED' | 'MEMORY_REJECTED' | 'MEMORY_RETRIEVED') => void = () => undefined) {}
  async createCandidate(input: MemoryCandidateInput, privacy: ConversationPrivacy = 'ALLOW_MEMORY'): Promise<MemoryCandidate | null> {
    if (privacy !== 'ALLOW_MEMORY' || sensitive.test(input.content) || !input.content.trim() || input.content.length > 10000) return null;
    if (!Number.isFinite(input.confidence) || input.confidence < 0 || input.confidence > 1) throw new Error('Candidate confidence is invalid.');
    const candidate: MemoryCandidate = { id: randomUUID(), content: input.content.trim(), category: input.category, importance: input.importance, source: input.source ?? 'CONVERSATION', sourceConversationId: input.sourceConversationId, sourceMessageId: input.sourceMessageId, confidence: input.confidence, reason: input.reason.slice(0, 500), status: 'CANDIDATE', createdAt: new Date().toISOString() };
    this.database.prepare(`INSERT INTO memory_candidates (${candidateColumns}) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(candidate.id, candidate.content, candidate.category, candidate.importance, candidate.source, candidate.sourceConversationId ?? null, candidate.sourceMessageId ?? null, candidate.confidence, candidate.reason, candidate.status, candidate.createdAt); this.onEvent('MEMORY_CANDIDATE_CREATED'); return candidate;
  }
  async listCandidates(): Promise<MemoryCandidate[]> { return (this.database.prepare(`SELECT ${candidateColumns} FROM memory_candidates WHERE status = 'CANDIDATE' ORDER BY created_at DESC`).all() as CandidateRow[]).map(mapCandidate); }
  async approveCandidate(id: string): Promise<Memory> { const candidate = this.getCandidate(id); if (!candidate || candidate.status !== 'CANDIDATE') throw new Error('Memory candidate not found.'); this.database.prepare(`UPDATE memory_candidates SET status = 'APPROVED' WHERE id = ?`).run(id); const memory = this.memories.createMemory({ content: candidate.content, category: candidate.category, importance: candidate.importance, source: 'USER_APPROVED', tags: [], metadata: { sourceCandidateId: candidate.id } }); this.onEvent('MEMORY_APPROVED'); return memory; }
  async rejectCandidate(id: string): Promise<boolean> { const result = this.database.prepare(`UPDATE memory_candidates SET status = 'REJECTED' WHERE id = ? AND status = 'CANDIDATE'`).run(id); if (result.changes) this.onEvent('MEMORY_REJECTED'); return result.changes === 1; }
  async retrieveRelevant(query: string): Promise<Memory[]> {
    const authorization = this.permissions.authorizeAction({ capabilityId: 'memory.read', resource: 'memory' });
    if (authorization.result !== 'ALLOWED' || !query.trim()) return [];
    const results = this.memories.searchMemories({ query: query.trim().slice(0, 500), limit: 20 }).filter((memory) => !memory.archived).sort((left, right) => this.score(right, query) - this.score(left, query)).slice(0, 5).map((memory) => ({ ...memory, content: memory.content.slice(0, 1200) }));
    this.onEvent('MEMORY_RETRIEVED'); return results;
  }
  async createStyleProfile(input: Omit<CommunicationStyleProfile, 'id' | 'createdAt' | 'updatedAt'>): Promise<CommunicationStyleProfile> { if (input.approvalState !== 'APPROVED') throw new Error('Style profiles require approval.'); const now = new Date().toISOString(); const profile = { ...input, id: randomUUID(), createdAt: now, updatedAt: now }; this.database.prepare('INSERT INTO communication_style_profiles (id, source, approval_state, formality, verbosity, punctuation_style, emoji_usage, greeting_style, closing_style, humor_level, common_expressions_json, contact_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run(profile.id, profile.source, profile.approvalState, profile.formality, profile.verbosity, profile.punctuationStyle, profile.emojiUsage, profile.greetingStyle, profile.closingStyle, profile.humorLevel, JSON.stringify(profile.commonExpressions.slice(0, 20)), profile.contactId ?? null, profile.createdAt, profile.updatedAt); return profile; }
  async listStyleProfiles(): Promise<CommunicationStyleProfile[]> { const rows = this.database.prepare('SELECT * FROM communication_style_profiles WHERE approval_state = ? ORDER BY updated_at DESC').all('APPROVED') as Array<Record<string, unknown>>; return rows.map((row) => ({ id: String(row.id), source: row.source as CommunicationStyleProfile['source'], approvalState: 'APPROVED', formality: row.formality as CommunicationStyleProfile['formality'], verbosity: row.verbosity as CommunicationStyleProfile['verbosity'], punctuationStyle: String(row.punctuation_style), emojiUsage: row.emoji_usage as CommunicationStyleProfile['emojiUsage'], greetingStyle: String(row.greeting_style), closingStyle: String(row.closing_style), humorLevel: row.humor_level as CommunicationStyleProfile['humorLevel'], commonExpressions: JSON.parse(String(row.common_expressions_json)) as string[], contactId: row.contact_id ? String(row.contact_id) : undefined, createdAt: String(row.created_at), updatedAt: String(row.updated_at) })); }
  private getCandidate(id: string): MemoryCandidate | undefined { if (!/^[0-9a-f-]{36}$/.test(id)) throw new Error('Candidate ID is invalid.'); const row = this.database.prepare(`SELECT ${candidateColumns} FROM memory_candidates WHERE id = ?`).get(id) as CandidateRow | undefined; return row ? mapCandidate(row) : undefined; }
  private score(memory: Memory, query: string): number { const term = query.toLowerCase(); const content = memory.content.toLowerCase(); return (content.includes(term) ? 100 : 0) + ({ CRITICAL: 40, HIGH: 30, NORMAL: 20, LOW: 10 }[memory.importance]) + (memory.source === 'USER_APPROVED' || memory.source === 'USER_EXPLICIT' ? 20 : 0) + new Date(memory.updatedAt).getTime() / 1e13; }
}