import { randomUUID } from 'node:crypto';
import type Database from 'better-sqlite3';
import type { Routine, RoutineAction } from '../../shared/routineTypes';
import type { AuditService } from '../auditService';

export interface RoutineExecutors { desktopCommand: (command: string) => Promise<boolean>; notification: (title: string, body: string, silent?: boolean) => void; memory: (action: Record<string, string>) => Promise<boolean>; device: (action: Record<string, string>) => Promise<boolean>; }
const noopExecutors: RoutineExecutors = { desktopCommand: async () => false, notification: () => undefined, memory: async () => false, device: async () => false };

export class RoutineService {
  private readonly routines = new Map<string, Routine>();
  constructor(private readonly db: Database.Database, private readonly audit: AuditService, private readonly executors: RoutineExecutors = noopExecutors) { this.load(); }
  async list(): Promise<Routine[]> { return [...this.routines.values()].map(r => ({ ...r, trigger: { ...r.trigger }, actions: r.actions.map(a => ({ ...a, input: { ...a.input } })) })); }
  async create(input: Omit<Routine, 'id' | 'createdAt' | 'updatedAt'>): Promise<Routine> { this.validate(input); const now = new Date().toISOString(); const routine: Routine = { ...input, id: randomUUID(), createdAt: now, updatedAt: now }; this.routines.set(routine.id, routine); this.save(routine); this.audit.record('ROUTINE_CREATED', routine.id); return routine; }
  async update(id: string, input: Partial<Omit<Routine, 'id' | 'createdAt' | 'updatedAt'>>): Promise<Routine> { const current = this.routines.get(id); if (!current) throw new Error('Routine not found.'); const next: Routine = { ...current, ...input, trigger: { ...current.trigger, ...(input.trigger ?? {}) }, actions: input.actions ?? current.actions, updatedAt: new Date().toISOString() }; this.validate(next); this.routines.set(id, next); this.save(next); this.audit.record('ROUTINE_UPDATED', id); return next; }
  async remove(id: string): Promise<boolean> { if (!this.routines.has(id)) return false; this.routines.delete(id); this.db.prepare('DELETE FROM tesh_routines WHERE id=?').run(id); this.audit.record('ROUTINE_DELETED', id); return true; }
  async run(id: string, confirmed = false): Promise<{ ok: boolean; message: string }> { const routine = this.routines.get(id); if (!routine) throw new Error('Routine not found.'); if (!routine.enabled) return { ok: false, message: 'Routine is disabled.' }; for (const action of routine.actions) { if (action.requiresConfirmation && !confirmed) return { ok: false, message: `Confirmation required for ${action.type}.` }; const ok = await this.execute(action); if (!ok) return { ok: false, message: `${action.type} action failed or was unavailable.` }; } this.audit.record('ROUTINE_RUN', id); return { ok: true, message: 'Routine completed.' }; }
  private async execute(action: RoutineAction): Promise<boolean> { switch (action.type) { case 'DESKTOP_COMMAND': return this.executors.desktopCommand(action.input.command ?? ''); case 'NOTIFICATION': this.executors.notification(action.input.title ?? 'Tesh', action.input.message ?? '', action.input.silent === 'true'); return true; case 'MEMORY_ACTION': return this.executors.memory(action.input); case 'DEVICE_ACTION': return this.executors.device(action.input); default: return false; } }
  private validate(routine: Omit<Routine, 'id' | 'createdAt' | 'updatedAt'> | Routine): void { if (!routine.name.trim() || routine.name.length > 100) throw new Error('Routine name is invalid.'); if (!routine.trigger?.value || routine.trigger.value.length > 200) throw new Error('Routine trigger is invalid.'); if (!Array.isArray(routine.actions) || !routine.actions.length || routine.actions.length > 20) throw new Error('Routine actions are invalid.'); for (const action of routine.actions) { if (!action.id || !action.input || typeof action.requiresConfirmation !== 'boolean') throw new Error('Routine action is invalid.'); if (Object.keys(action.input).some(key => key.length > 80 || action.input[key].length > 2000)) throw new Error('Routine action input is invalid.'); } }
  private load(): void { this.db.exec('CREATE TABLE IF NOT EXISTS tesh_routines (id TEXT PRIMARY KEY,name TEXT NOT NULL,enabled INTEGER NOT NULL,trigger_json TEXT NOT NULL,actions_json TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)'); const rows=this.db.prepare('SELECT id,name,enabled,trigger_json,actions_json,created_at as createdAt,updated_at as updatedAt FROM tesh_routines').all() as Array<{id:string;name:string;enabled:number;trigger_json:string;actions_json:string;createdAt:string;updatedAt:string}>; for(const row of rows) this.routines.set(row.id,{id:row.id,name:row.name,enabled:Boolean(row.enabled),trigger:JSON.parse(row.trigger_json),actions:JSON.parse(row.actions_json),createdAt:row.createdAt,updatedAt:row.updatedAt}); }
  private save(routine:Routine):void{this.db.prepare('INSERT OR REPLACE INTO tesh_routines (id,name,enabled,trigger_json,actions_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').run(routine.id,routine.name,routine.enabled?1:0,JSON.stringify(routine.trigger),JSON.stringify(routine.actions),routine.createdAt,routine.updatedAt);}
}
