import { useEffect, useState } from 'react';
import type { ReactElement } from 'react';
import type { CommunicationSnapshot, MessageDraft, RecipientResolution } from '../../../shared/communicationTypes';

export function CommunicationPanel(): ReactElement | null {
  const bridge = window.tesh?.communication;
  const permissions = window.tesh?.permissions;
  const system = window.tesh?.system;
  const [snapshot, setSnapshot] = useState<CommunicationSnapshot>({ provider: 'MOCK', contacts: [] });
  const [recipient, setRecipient] = useState('');
  const [content, setContent] = useState('');
  const [message, setMessage] = useState('');
  useEffect(() => { if (bridge) void bridge.getSnapshot().then(setSnapshot); }, [bridge]);
  if (!bridge) return null;
  const refresh = async (): Promise<void> => setSnapshot(await bridge.getSnapshot());
  const resolve = async (): Promise<void> => { try { setSnapshot({ ...snapshot, resolution: await bridge.resolveRecipient(recipient) }); } catch (error) { setMessage(error instanceof Error ? error.message : 'Resolution failed.'); } };
  const create = async (): Promise<void> => { try { setSnapshot({ ...snapshot, draft: await bridge.createDraft({ recipientQuery: recipient, content, styleProfileUsed: 'approved style context when selected' }) }); setMessage('Draft created. Sending still requires explicit confirmation.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Draft creation failed.'); } };
  const update = async (draft: MessageDraft): Promise<void> => { try { setSnapshot({ ...snapshot, draft: await bridge.updateDraft(draft.id, content) }); } catch (error) { setMessage(error instanceof Error ? error.message : 'Draft update failed.'); } };
  const confirm = async (approved: boolean): Promise<void> => { if (!snapshot.draft) return; setSnapshot({ ...snapshot, draft: await bridge.confirmSend(snapshot.draft.id, approved) }); };
  return <section className="communication-panel" aria-label="Development communications panel"><div className="memory-heading"><div><p className="panel-label">Development only</p><h2>Communications foundation</h2></div><span>{snapshot.provider} provider</span></div><div className="voice-actions"><button type="button" onClick={() => void system?.setDevelopmentSession(true)}>Set mock verified session</button><button type="button" onClick={() => void system?.setDevelopmentSession(false)}>Clear session</button><button type="button" onClick={() => void permissions?.grant('COMMUNICATE', undefined, 'SESSION')}>Grant communication permission</button></div><div className="communication-form"><input value={recipient} onChange={(event) => setRecipient(event.target.value)} placeholder="Recipient, e.g. Sarah" aria-label="Recipient" /><textarea value={content} onChange={(event) => setContent(event.target.value)} placeholder="Draft message content" aria-label="Draft message" /><div className="voice-actions"><button type="button" onClick={() => void resolve()}>Resolve recipient</button><button type="button" onClick={() => void create()}>Create draft</button></div></div>{snapshot.resolution ? <div className="communication-readout"><span className="panel-label">Resolution</span><strong>{snapshot.resolution.status} · {snapshot.resolution.matches.map((match) => match.displayName).join(', ') || 'no matches'}</strong></div> : null}{snapshot.draft ? <div className="draft-card"><span className="panel-label">Draft · {snapshot.draft.status}</span><p><strong>Recipient:</strong> {snapshot.draft.recipient.displayName}</p><textarea value={content || snapshot.draft.content} onChange={(event) => setContent(event.target.value)} aria-label="Edit draft message" /><p><strong>Style:</strong> {snapshot.draft.styleProfileUsed || 'none'} · <strong>Authorization:</strong> {snapshot.draft.authorizationResult}</p>{snapshot.draft.status === 'AWAITING_CONFIRMATION' ? <div className="voice-actions"><button type="button" onClick={() => void update(snapshot.draft!)}>Save edit and ask again</button><button type="button" onClick={() => void confirm(true)}>SEND IT</button><button type="button" onClick={() => void confirm(false)}>Don't send</button></div> : null}</div> : null}<p className="preview-copy">Mock provider only. No accounts, credentials, cookies, tokens, or external messages are accessed. A permission grant never substitutes for current send confirmation.</p><p className="memory-message" aria-live="polite">{message}</p></section>;
}