import type { Capability } from '../../shared/permissionTypes';

const now = '2026-01-01T00:00:00.000Z';
export const capabilities: readonly Capability[] = [
  { id: 'microphone.listen', name: 'Listen through microphone', description: 'Capture live microphone amplitude and transient speech transcripts.', category: 'voice', requiredPermissions: ['MICROPHONE'], riskLevel: 'HIGH', requiresConfirmation: false, supportsOffline: false, enabled: true, createdAt: now, updatedAt: now },
  { id: 'file.read', name: 'Read authorized files', description: 'Read supported text files within an approved scope.', category: 'filesystem', requiredPermissions: ['READ'], riskLevel: 'NORMAL', requiresConfirmation: false, supportsOffline: true, enabled: true, createdAt: now, updatedAt: now },
  { id: 'file.display', name: 'Display authorized files', description: 'Open an authorized file for the user.', category: 'filesystem', requiredPermissions: ['READ'], riskLevel: 'NORMAL', requiresConfirmation: false, supportsOffline: true, enabled: true, createdAt: now, updatedAt: now },
  { id: 'file.create', name: 'Create authorized files', description: 'Create a new file in an approved scope.', category: 'filesystem', requiredPermissions: ['WRITE'], riskLevel: 'NORMAL', requiresConfirmation: false, supportsOffline: true, enabled: true, createdAt: now, updatedAt: now },
  { id: 'file.rename', name: 'Rename authorized files', description: 'Rename an authorized file.', category: 'filesystem', requiredPermissions: ['WRITE'], riskLevel: 'NORMAL', requiresConfirmation: false, supportsOffline: true, enabled: true, createdAt: now, updatedAt: now },
  { id: 'file.move', name: 'Move authorized files', description: 'Move an authorized file.', category: 'filesystem', requiredPermissions: ['WRITE'], riskLevel: 'NORMAL', requiresConfirmation: false, supportsOffline: true, enabled: true, createdAt: now, updatedAt: now },
  { id: 'system.diagnostics', name: 'Read system diagnostics', description: 'Read safe local system diagnostics.', category: 'system', requiredPermissions: ['SYSTEM_DIAGNOSTICS'], riskLevel: 'NORMAL', requiresConfirmation: false, supportsOffline: true, enabled: true, createdAt: now, updatedAt: now },
  { id: 'contact.read', name: 'Read contacts', description: 'Resolve contacts through an approved provider.', category: 'communication', requiredPermissions: ['COMMUNICATE'], riskLevel: 'NORMAL', requiresConfirmation: false, supportsOffline: true, enabled: true, createdAt: now, updatedAt: now },
  { id: 'message.draft', name: 'Create message drafts', description: 'Create drafts without sending them.', category: 'communication', requiredPermissions: ['COMMUNICATE'], riskLevel: 'NORMAL', requiresConfirmation: false, supportsOffline: true, enabled: true, createdAt: now, updatedAt: now },
  { id: 'file.read', name: 'Read authorized files', description: 'Read supported text files within an approved scope.', category: 'filesystem', requiredPermissions: ['READ'], riskLevel: 'NORMAL', requiresConfirmation: false, supportsOffline: true, enabled: true, createdAt: now, updatedAt: now },
  { id: 'file.display', name: 'Display authorized files', description: 'Open an authorized file for the user.', category: 'filesystem', requiredPermissions: ['READ'], riskLevel: 'NORMAL', requiresConfirmation: false, supportsOffline: true, enabled: true, createdAt: now, updatedAt: now },
  { id: 'file.create', name: 'Create authorized files', description: 'Create a new file in an approved scope.', category: 'filesystem', requiredPermissions: ['WRITE'], riskLevel: 'NORMAL', requiresConfirmation: false, supportsOffline: true, enabled: true, createdAt: now, updatedAt: now },
  { id: 'file.rename', name: 'Rename authorized files', description: 'Rename a file within an approved scope.', category: 'filesystem', requiredPermissions: ['WRITE'], riskLevel: 'NORMAL', requiresConfirmation: false, supportsOffline: true, enabled: true, createdAt: now, updatedAt: now },
  { id: 'file.move', name: 'Move authorized files', description: 'Move a file within approved scopes.', category: 'filesystem', requiredPermissions: ['WRITE'], riskLevel: 'NORMAL', requiresConfirmation: false, supportsOffline: true, enabled: true, createdAt: now, updatedAt: now },
  { id: 'system.diagnostics', name: 'Read system diagnostics', description: 'Read safe local system diagnostics.', category: 'system', requiredPermissions: ['SYSTEM_DIAGNOSTICS'], riskLevel: 'NORMAL', requiresConfirmation: false, supportsOffline: true, enabled: true, createdAt: now, updatedAt: now },
  { id: 'memory.read', name: 'Read local memories', description: 'Read explicitly stored Tesh memories.', category: 'memory', requiredPermissions: ['MEMORY_ACCESS'], riskLevel: 'NORMAL', requiresConfirmation: false, supportsOffline: true, enabled: true, createdAt: now, updatedAt: now },
  { id: 'file.read', name: 'Read authorized files', description: 'Future file reading within an approved scope.', category: 'filesystem', requiredPermissions: ['READ'], riskLevel: 'NORMAL', requiresConfirmation: false, supportsOffline: true, enabled: false, createdAt: now, updatedAt: now },
  { id: 'file.delete', name: 'Delete authorized files', description: 'Future deletion of files within an approved scope.', category: 'filesystem', requiredPermissions: ['DELETE'], riskLevel: 'HIGH', requiresConfirmation: true, supportsOffline: true, enabled: true, createdAt: now, updatedAt: now },
  { id: 'camera.access', name: 'Access authorized camera', description: 'Future access to a user-authorized camera.', category: 'camera', requiredPermissions: ['CAMERA'], riskLevel: 'HIGH', requiresConfirmation: true, supportsOffline: true, enabled: false, createdAt: now, updatedAt: now },
  { id: 'message.send', name: 'Send communication', description: 'Send a confirmed message through an approved provider.', category: 'communication', requiredPermissions: ['COMMUNICATE'], riskLevel: 'HIGH', requiresConfirmation: true, supportsOffline: true, enabled: true, createdAt: now, updatedAt: now },
  { id: 'system.inspect', name: 'Inspect system diagnostics', description: 'Future access to approved system metrics.', category: 'system', requiredPermissions: ['SYSTEM_DIAGNOSTICS'], riskLevel: 'NORMAL', requiresConfirmation: false, supportsOffline: true, enabled: false, createdAt: now, updatedAt: now }
];
