import { randomUUID } from 'node:crypto';
import type { ActionAuthorization, ActionAuthorizationRequest, Capability, IdentityState, PermissionDuration, PermissionGrant, PermissionState, PermissionType, TrustLevel } from '../../shared/permissionTypes';
import { capabilities } from './permissionRegistry';
import { PermissionRepository } from './permissionRepository';

export class PermissionService {
  private trust: TrustLevel = 'LIMITED';
  private identity: IdentityState = 'UNKNOWN';
  constructor(private readonly repository: PermissionRepository, private readonly onEvent?: (event: string, id?: string) => void) {}
  listCapabilities(): Capability[] { return [...capabilities]; }
  listPermissions(): PermissionGrant[] { return this.repository.list().filter((grant) => !this.isExpired(grant)); }
  grantPermission(permission: PermissionType, scope: string | undefined, duration: PermissionDuration): PermissionGrant { this.validatePermission(permission); this.validateScope(scope); const now = new Date(); const grant: PermissionGrant = { id: randomUUID(), permission, state: 'GRANTED', scope: scope?.trim() || undefined, duration, expiresAt: duration === 'UNTIL_REVOKED' ? undefined : new Date(now.getTime() + (duration === 'ONCE' ? 60 * 60 * 1000 : 24 * 60 * 60 * 1000)).toISOString(), createdAt: now.toISOString(), updatedAt: now.toISOString() }; const result = this.repository.save(grant); this.onEvent?.('PERMISSION_GRANTED', result.id); return result; }
  denyPermission(permission: PermissionType, scope?: string): PermissionGrant { this.validatePermission(permission); this.validateScope(scope); const now = new Date().toISOString(); const grant: PermissionGrant = { id: randomUUID(), permission, state: 'DENIED', scope: scope?.trim() || undefined, duration: 'UNTIL_REVOKED', createdAt: now, updatedAt: now }; const result = this.repository.save(grant); this.onEvent?.('PERMISSION_DENIED', result.id); return result; }
  revokePermission(id: string): boolean { if (!this.isId(id)) throw new Error('Permission ID is invalid.'); const removed = this.repository.remove(id); if (removed) this.onEvent?.('PERMISSION_REVOKED', id); return removed; }
  checkPermission(permission: PermissionType, scope?: string): PermissionState { this.validatePermission(permission); this.validateScope(scope); const matching = this.repository.findMatching(permission, scope).filter((grant) => !this.isExpired(grant)); if (matching.some((grant) => grant.state === 'DENIED')) return 'DENIED'; if (matching.some((grant) => grant.state === 'GRANTED')) return 'GRANTED'; return 'UNKNOWN'; }
  authorizeAction(request: ActionAuthorizationRequest): ActionAuthorization { const capability = capabilities.find((item) => item.id === request.capabilityId); if (!capability || !capability.enabled) return { result: 'DENIED', capabilityId: request.capabilityId, permissionStates: {}, reason: 'Capability is unavailable.', requiresConfirmation: false }; const permissions = request.requestedPermissions ?? capability.requiredPermissions; const permissionStates = Object.fromEntries(permissions.map((permission) => [permission, this.checkPermission(permission, request.resource)])) as Record<PermissionType, PermissionState>; if (Object.values(permissionStates).some((state) => state === 'DENIED')) return { result: 'DENIED', capabilityId: capability.id, permissionStates, reason: 'A required permission is denied.', requiresConfirmation: capability.requiresConfirmation }; if (Object.values(permissionStates).some((state) => state !== 'GRANTED')) return { result: 'REQUIRES_PERMISSION', capabilityId: capability.id, permissionStates, reason: 'Explicit permission is required.', requiresConfirmation: capability.requiresConfirmation }; if (capability.requiresConfirmation && !request.confirmed) return { result: 'REQUIRES_CONFIRMATION', capabilityId: capability.id, permissionStates, reason: 'Explicit action confirmation is required.', requiresConfirmation: true }; this.onEvent?.('ACTION_AUTHORIZED', capability.id); return { result: 'ALLOWED', capabilityId: capability.id, permissionStates, reason: 'All required permissions are granted.', requiresConfirmation: capability.requiresConfirmation }; }
  getTrust(): { trust: TrustLevel; identity: IdentityState } { return { trust: this.trust, identity: this.identity }; }
  private isExpired(grant: PermissionGrant): boolean { return Boolean(grant.expiresAt && new Date(grant.expiresAt).getTime() <= Date.now()); }
  private validatePermission(permission: string): void { if (!['READ', 'WRITE', 'EXECUTE', 'DELETE', 'COMMUNICATE', 'LOCATION', 'MICROPHONE', 'CAMERA', 'SYSTEM_DIAGNOSTICS', 'DEVICE_ACCESS', 'NETWORK', 'MEMORY_ACCESS'].includes(permission)) throw new Error('Permission type is invalid.'); }
  private validateScope(scope?: string): void { if (scope !== undefined && (typeof scope !== 'string' || scope.trim().length > 1000)) throw new Error('Permission scope is invalid.'); }
  private isId(value: string): boolean { return typeof value === 'string' && /^[0-9a-f-]{36}$/.test(value); }
}
